In [3]:
print("This line will be printed")

This line will be printed


In [4]:
x = 1
if x == 1:
    print("x is 1.")

x is 1.


In [5]:
print(4+5)

9


In [6]:
height = 1.79
weight = 68.7
x = "body mass index"
type(x)

str

In [7]:
words = ['cat', "window", "defenestrate"]
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


In [8]:
price = 100.50
price + 1

word = "Python"
word[2:]

'thon'

In [9]:
squares = [1, 4, 9, 16, 25]
squares[:] = []
print(len(squares))

0


In [10]:
# Fibonacci series:
a, b = 0, 1
while a < 1000:
  a, b = b, a + b
  print(a)

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597


In [11]:
users = {
  'Hans': 'active',
  'Éléonore': 'inactive', 
  '景太郎': 'active',
}

for user, status in users.copy().items():
  if status == 'inactive':
    del users[user]

users

{'Hans': 'active', '景太郎': 'active'}

In [12]:
point = (4, 1)

match point:
  case(0, 0):
    print("Origin")
  case(0, y):
    print(f"pt lies on y-axis with y={y}")
  case(x, 0):
    print(f"pt lies on x-axis with x={x}")
  case(x, y):
    print(f"pt is on ({x}, {y})")
  case _:
    raise ValueError("Not a point")

pt is on (4, 1)


In [13]:
class Point:
  __match_args__ = ('x', 'y')
  
  def __init__(self, x, y):
    self.x = x
    self.y = y

pt = Point(1, 2)
print(pt)

In [14]:
def fib(n):
  result = []
  a, b = 0, 1
  while a < n:
    result.append(a)
    a, b = b, a + b
  return result;

print(fib(100))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [15]:
def ask_ok(prompt, retries = 4, reminder = "Please try again!"):
  while True:
    reply = input(prompt)
    if reply in { 'y', 'ye', 'yes' }:
      return True
    if reply in { 'n', 'no', 'nop', 'nope' }:
      return False
    
    retries -= 1
    if retries <= 0:
      raise ValueError('invalid user input')
    
    print(reminder)

ask_ok("Are you good?", 2)

Please try again!


<class 'ValueError'>: invalid user input

Are you good? yes
Are you good? ab


In [21]:
from collections import deque

queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")
queue.popleft()
queue

deque(['John', 'Michael', 'Terry'])

In [23]:
from math import pi
[str(round(pi, i)) for i in range(6)]

['3.0', '3.1', '3.14', '3.142', '3.1416', '3.14159']

In [26]:
matrix = [
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
]

[[row[i] for row in matrix] for i in range(4)]

transposed = []
for i in range(4):
  transposed.append([row[i] for row in matrix])

print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [31]:
t = (1, 2, 3)
print(t)

(1, 2, 3)


In [34]:
import sys
dir(sys)

['__breakpointhook__',
 '__displayhook__',
 '__doc__',
 '__excepthook__',
 '__interactivehook__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__stderr__',
 '__stdin__',
 '__stdout__',
 '__unraisablehook__',
 '_base_executable',
 '_clear_type_cache',
 '_current_exceptions',
 '_current_frames',
 '_debugmallocstats',
 '_emscripten_info',
 '_framework',
 '_getframe',
 '_getquickenedcount',
 '_git',
 '_home',
 '_stdlib_dir',
 '_xoptions',
 'abiflags',
 'addaudithook',
 'api_version',
 'argv',
 'audit',
 'base_exec_prefix',
 'base_prefix',
 'breakpointhook',
 'builtin_module_names',
 'byteorder',
 'call_tracing',
 'copyright',
 'displayhook',
 'dont_write_bytecode',
 'exc_info',
 'excepthook',
 'exception',
 'exec_prefix',
 'executable',
 'exit',
 'flags',
 'float_info',
 'float_repr_style',
 'get_asyncgen_hooks',
 'get_coroutine_origin_tracking_depth',
 'get_int_max_str_digits',
 'getallocatedblocks',
 'getdefaultencoding',
 'getdlopenflags',
 'getfilesystemencodeerrors',
 'g

In [36]:
import numpy as np
import matplotlib as mpl

In [49]:
a = np.arange(15).reshape(3,5)
print(a)

a.itemsize

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


4

In [54]:
b = np.array([6.0,7.0,8.0])
b.dtype

dtype('float64')

In [58]:
c = np.array([[1,2], [3,4]], dtype=complex)
print(c)
c.dtype

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


dtype('complex128')

In [66]:
d = np.empty((2, 3, 4), dtype=np.int16)
print(d)

[[[ -1504    961 -11540     59]
  [-23720    422      0      0]
  [     0      0      0      0]]

 [[  9144    190      0      0]
  [ 18736   1016     17      0]
  [  8448   1016 -11580     59]]]


In [68]:
large = np.arange(10000)
large.reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [74]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a-b
print(a)
a < 35

[20 30 40 50]


array([ True,  True, False, False])

In [97]:
A = np.array([1, 1, 0, 1]).reshape(2,2)
B = np.array([2,0,3,4]).reshape(2,2)
A.dot(B)

rg = np.random.default_rng(1)
b = rg.random((2,3))*10
a = np.ones((2,3), dtype = int) * 3
b += a

print(b.sum())
print(b.min())
print(b.max())

50.9025228186613
4.441596127196338
12.504636963259353


In [103]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.cumsum(axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [109]:
B = np.arange(12).reshape(3,4)
print(B)
np.transpose(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [114]:
a = np.arange(10)**3
print(a)
a[0:6:2] = 1000
print(a)

[  0   1   8  27  64 125 216 343 512 729]
[1000    1 1000   27 1000  125  216  343  512  729]


In [123]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype = int)
print(b)

b[1:4, 1:4]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [134]:
c = np.array([0, 1, 2, 10, 12, 13, 100, 101, 102, 110, 112, 113]).reshape(2,2,3)
print(c)
print('---')
for row in c:
    print(row)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
---
[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [2]:
import numpy as np
rg = np.random.default_rng(2)
a = np.floor(10 * rg.random((2,2, 3)))
b = np.floor(10 * rg.random((2,2, 3)))
print(a)
print(b)
print("---")
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[[2. 2. 8.]
  [0. 6. 7.]]

 [[1. 0. 2.]
  [6. 5. 1.]]]
[[[4. 6. 4.]
  [6. 9. 6.]]

 [[3. 1. 3.]
  [5. 8. 7.]]]
---
[[[2. 2. 8.]
  [0. 6. 7.]]

 [[1. 0. 2.]
  [6. 5. 1.]]

 [[4. 6. 4.]
  [6. 9. 6.]]

 [[3. 1. 3.]
  [5. 8. 7.]]]
[[[2. 2. 8.]
  [0. 6. 7.]
  [4. 6. 4.]
  [6. 9. 6.]]

 [[1. 0. 2.]
  [6. 5. 1.]
  [3. 1. 3.]
  [5. 8. 7.]]]


In [3]:
p = 103
print(pow(10, -1, p))

31


In [4]:
10 * 31 % p

1